name: Docs from Polynote

on: 
  schedule:
    - cron: '*/15 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Docs
      run: |
        git clone https://github.com/polynote/polynote.git
        cp polynote/docs/*.md ./docs/
        rm -r polynote/
        git config --global user.email "polynote-ci@polynote.org"
        git config --global user.name "Polynote CI"
        git commit -am "automated docs update" || true
    - name: Create PR with changes
      uses: peter-evans/create-pull-request@v1.5.4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
