name: Docs from Polynote

on: 
  push:
    branches:
      - master
  schedule:
    - cron: '*/15 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Docs
      run: |
        set -x
        git clone https://github.com/polynote/polynote.git
        cp -r polynote/docs/. docs/
        git status
        rm -r polynote/
        git config --global user.email "polynote-ci@polynote.org"
        git config --global user.name "Polynote CI"
        git commit -am "automated docs update" || true
    - name: Create PR with changes
      uses: peter-evans/create-pull-request@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
